<script>
  let { voxelData, settings } = $props();
  
  let activeView = $state('visual');
  let currentLayer = $state(0);

  const stitchNames = {
    sc: 'single crochet',
    hdc: 'half double crochet',
    dc: 'double crochet'
  };

  const stitchAbbrev = {
    sc: 'sc',
    hdc: 'hdc',
    dc: 'dc'
  };

  $effect(() => {
    if (voxelData) {
      currentLayer = Math.floor(voxelData.dimensions.z / 2);
    }
  });

  function generateWrittenInstructions() {
    if (!voxelData) return [];
    
    const instructions = [];
    const { voxels, dimensions } = voxelData;
    const stitch = stitchAbbrev[settings.stitchType];
    
    for (let z = 0; z < dimensions.z; z++) {
      const layerInstructions = [];
      layerInstructions.push(`Round ${z + 1}:`);
      
      let stitchCount = 0;
      let currentColor = -1;
      let colorRuns = [];
      
      // Count stitches per row
      for (let y = 0; y < dimensions.y; y++) {
        for (let x = 0; x < dimensions.x; x++) {
          const colorIndex = voxels[z][y][x];
          if (colorIndex >= 0) {
            if (colorIndex !== currentColor) {
              if (stitchCount > 0) {
                colorRuns.push({ color: currentColor, count: stitchCount });
              }
              currentColor = colorIndex;
              stitchCount = 1;
            } else {
              stitchCount++;
            }
          }
        }
      }
      
      if (stitchCount > 0) {
        colorRuns.push({ color: currentColor, count: stitchCount });
      }
      
      if (colorRuns.length > 0) {
        const runDescriptions = colorRuns.map(run => {
          const colorHex = settings.colorPalette[run.color] || '#ccc';
          return `${run.count} ${stitch} in Color ${run.color + 1} (${colorHex})`;
        });
        layerInstructions.push(runDescriptions.join(', '));
        
        const totalStitches = colorRuns.reduce((sum, run) => sum + run.count, 0);
        layerInstructions.push(`(${totalStitches} stitches total)`);
      } else {
        layerInstructions.push('Skip this round (no stitches)');
      }
      
      instructions.push(layerInstructions);
    }
    
    return instructions;
  }

  function downloadPattern() {
    const instructions = generateWrittenInstructions();
    let text = `CROCHET PATTERN\n`;
    text += `Generated by StitchCraft\n`;
    text += `=====================================\n\n`;
    text += `Stitch Type: ${stitchNames[settings.stitchType]}\n`;
    text += `Dimensions: ${voxelData.dimensions.x}x${voxelData.dimensions.y}x${voxelData.dimensions.z}\n`;
    text += `Colors: ${settings.colorPalette.join(', ')}\n\n`;
    text += `INSTRUCTIONS\n`;
    text += `=====================================\n\n`;
    
    instructions.forEach(layer => {
      text += layer.join('\n') + '\n\n';
    });
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'crochet-pattern.txt';
    a.click();
    URL.revokeObjectURL(url);
  }
</script>

<div class="bg-card rounded-2xl border border-border shadow-sm overflow-hidden">
  <div class="p-6 border-b border-border flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
    <div>
      <h2 class="text-xl font-semibold text-card-foreground">Your Crochet Pattern</h2>
      <p class="text-sm text-muted-foreground mt-1">
        {voxelData.fileName || voxelData.shapeName} - {voxelData.dimensions.x}x{voxelData.dimensions.y}x{voxelData.dimensions.z} stitches
      </p>
    </div>
    <button
      onclick={downloadPattern}
      class="px-4 py-2 bg-primary text-primary-foreground text-sm font-medium rounded-lg hover:opacity-90 transition-opacity flex items-center gap-2"
    >
      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
      </svg>
      Download Pattern
    </button>
  </div>

  <!-- View Toggle -->
  <div class="border-b border-border">
    <div class="flex">
      <button
        onclick={() => activeView = 'visual'}
        class="flex-1 px-4 py-3 text-sm font-medium transition-colors border-b-2 {activeView === 'visual' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}"
      >
        Visual Grid
      </button>
      <button
        onclick={() => activeView = 'written'}
        class="flex-1 px-4 py-3 text-sm font-medium transition-colors border-b-2 {activeView === 'written' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}"
      >
        Written Instructions
      </button>
    </div>
  </div>

  <div class="p-6">
    {#if activeView === 'visual'}
      <!-- Layer Selector -->
      <div class="mb-4">
        <label for="layer-selector" class="block text-sm font-medium text-foreground mb-2">
          Layer {currentLayer + 1} of {voxelData.dimensions.z}
        </label>
        <input
          id="layer-selector"
          type="range"
          min="0"
          max={voxelData.dimensions.z - 1}
          bind:value={currentLayer}
          class="w-full h-2 bg-muted rounded-lg appearance-none cursor-pointer accent-primary"
        />
      </div>

      <!-- Visual Grid -->
      <div class="overflow-auto max-h-96 border border-border rounded-lg p-4 bg-muted/30">
        <div class="inline-grid gap-px" style="grid-template-columns: repeat({voxelData.dimensions.x}, minmax(0, 1fr));">
          {#each voxelData.voxels[currentLayer] as row}
            {#each row as cell}
              <div
                class="w-4 h-4 sm:w-5 sm:h-5 rounded-sm transition-colors"
                style="background-color: {cell >= 0 ? settings.colorPalette[cell] || '#ccc' : 'transparent'}; {cell >= 0 ? 'border: 1px solid rgba(0,0,0,0.1);' : ''}"
                title={cell >= 0 ? `Color ${cell + 1}` : 'Empty'}
              ></div>
            {/each}
          {/each}
        </div>
      </div>

      <!-- Color Legend -->
      <div class="mt-4 flex flex-wrap gap-3">
        {#each settings.colorPalette as color, i}
          <div class="flex items-center gap-2">
            <div class="w-4 h-4 rounded" style="background-color: {color}; border: 1px solid rgba(0,0,0,0.1);"></div>
            <span class="text-xs text-muted-foreground">Color {i + 1}</span>
          </div>
        {/each}
      </div>
    {:else}
      <!-- Written Instructions -->
      <div class="space-y-4 max-h-96 overflow-auto">
        <div class="bg-muted/50 rounded-lg p-4">
          <h3 class="font-semibold text-foreground mb-2">Materials Needed</h3>
          <ul class="text-sm text-muted-foreground space-y-1">
            <li>Yarn in {settings.colorPalette.length} colors</li>
            <li>Crochet hook appropriate for your yarn weight</li>
            <li>Stitch markers</li>
            <li>Stuffing material</li>
          </ul>
        </div>

        <div class="bg-muted/50 rounded-lg p-4">
          <h3 class="font-semibold text-foreground mb-2">Abbreviations</h3>
          <p class="text-sm text-muted-foreground">
            {settings.stitchType} = {stitchNames[settings.stitchType]}
          </p>
        </div>

        <div class="space-y-3">
          {#each generateWrittenInstructions() as layer}
            <div class="border-l-2 border-primary/30 pl-4">
              {#each layer as line, j}
                <p class="text-sm {j === 0 ? 'font-semibold text-foreground' : 'text-muted-foreground'}">
                  {line}
                </p>
              {/each}
            </div>
          {/each}
        </div>
      </div>
    {/if}
  </div>
</div>
